/**
 * Type definitions for Saberloop.
 * Used for documentation, type checking, and IDE autocomplete.
 * @module types
 */

// ============================================
// Quiz & Question Types
// ============================================

/**
 * A single quiz question
 * @typedef {Object} Question
 * @property {string} question - The question text
 * @property {string[]} options - Array of 4 answer options (A, B, C, D)
 * @property {number} correctIndex - Index of correct answer (0-3)
 * @property {string} [explanation] - Optional explanation of the answer
 * @property {string} [difficulty] - Optional difficulty level
 */

/**
 * Quiz generation result from API
 * @typedef {Object} QuizResult
 * @property {string} language - Language code (e.g., 'EN-US', 'PT-PT')
 * @property {Question[]} questions - Array of generated questions
 */

/**
 * A saved quiz session
 * @typedef {Object} QuizSession
 * @property {number} [id] - Unique session ID (auto-generated by IndexedDB)
 * @property {string} topic - Quiz topic
 * @property {string} gradeLevel - Education level
 * @property {Question[]} questions - Array of questions
 * @property {number[]} userAnswers - User's selected answers (indices)
 * @property {number} score - Number of correct answers
 * @property {number} totalQuestions - Total number of questions
 * @property {string} timestamp - ISO timestamp of when quiz was taken
 * @property {string} [language] - Language code used for generation
 */

// ============================================
// Settings Types
// ============================================

/**
 * Application settings
 * @typedef {Object} AppSettings
 * @property {string} gradeLevel - Default education level
 * @property {string} questionsPerQuiz - Number of questions ('5', '10', '15')
 * @property {string} language - UI language code
 * @property {boolean} soundEnabled - Whether sounds are enabled
 * @property {boolean} hapticEnabled - Whether haptic feedback is enabled
 */

// ============================================
// Auth Types
// ============================================

/**
 * OpenRouter authentication state
 * @typedef {Object} AuthState
 * @property {boolean} isConnected - Whether user is authenticated
 * @property {string|null} apiKey - OpenRouter API key (or null)
 * @property {string|null} userCode - User's OpenRouter code
 */

/**
 * OAuth callback parameters
 * @typedef {Object} OAuthCallback
 * @property {string} code - Authorization code from OAuth flow
 * @property {string} [error] - Error code if OAuth failed
 * @property {string} [error_description] - Human-readable error message
 */

// ============================================
// API Types
// ============================================

/**
 * Options for quiz generation
 * @typedef {Object} GenerateOptions
 * @property {string} [language='en'] - Language code for generation
 * @property {number} [questionCount=5] - Number of questions to generate
 * @property {Question[]} [previousQuestions=[]] - Questions to avoid duplicating
 */

/**
 * Options for explanation generation
 * @typedef {Object} ExplanationOptions
 * @property {string} [language='en'] - Language code for explanation
 */

// ============================================
// Telemetry Types
// ============================================

/**
 * Telemetry event
 * @typedef {Object} TelemetryEvent
 * @property {string} event - Event name
 * @property {Object} [data] - Event-specific data
 * @property {string} timestamp - ISO timestamp
 * @property {string} sessionId - Browser session ID
 */

// ============================================
// Router Types
// ============================================

/**
 * Route definition
 * @typedef {Object} Route
 * @property {string} path - URL path pattern
 * @property {Function} handler - View handler function
 * @property {string} [title] - Page title
 */

/**
 * Navigation options
 * @typedef {Object} NavigateOptions
 * @property {boolean} [replace=false] - Replace current history entry
 * @property {Object} [state] - State to pass to the route
 */

export {};
